### ISSUE TITLE
March 3, 2020 | Code-Review : The Poodles

### ISSUE THREAD

**Issue by sz16900** [Flakster/Tic-Tac-Toe#3]
Great start of the project, Carlos. The game is looking good, clean and sleek.

I have a quick suggestion: why don't you try to keep players' scores at the end of the game? That way the players don't have to keep typing their names when the game.

**Comment by Meltrust** [comment]
Nice Job Carlos!

You could use 3 simple 3-6 element arrays to show the board after a player moves.

|o|x|o|
|x|x|o|
|o|x|o|

**Comment by Flakster** [comment]
Your suggestions have been incorporated to the program. Thanks!
