### ISSUE TITLE
March 6, 2020 | Code-Review : The Poodles

### ISSUE THREAD

**Issue by sz16900** [Flakster/Tic-Tac-Toe#5]
Your game looks sleek and fun. @Flakster please do not disable the linter files; they are there to enforce good practice :joy:. Happy Coding

**Comment by Meltrust** [comment]
Hey Carlos super nice job! Just nitpicking when you play, the x's and the o's are not centered.

**Comment by Flakster** [comment]
Your suggestions have been included in the new version. Thanks for your feedback!
